export let formData = {
  campaignName: "",
    description: "",
    gender: "",
    worktype: "",
    selectedOptionsindustry: [],
    selectedOptionslocation: [],
    selectedOptionsplatform: [],
    startDate: "",
    endDate: "",
    postCount: 0,
    reelCount: 0,
    storyCount: 0,
    payment: false,
    fixed: false,
    nagotiable: false,
    fixedAmt: null,
    min: null,
    range: 0,
    max: null,
    product: false,
    productDesc: "",
    link: "",
    upload: "",
};
